services:
    e-wallet:
        build:
         context: ../
         dockerfile: cmd/e-wallet-server/Dockerfile
        ports:
         - "8080:8080" # REST API
        depends_on:
         - migrate
        volumes:
         - ./../configs/e-wallet.yml:/etc/e-wallet/e-wallet.yml

    migrate:
        image: migrate/migrate:v4.17.0
        command: ["-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable", "up"]
        depends_on:
          postgres:
            condition: service_healthy
        volumes:
         - ./../migrations:/migrations

    # Create service with PostgreSQL.
    postgres:
        image: postgres:17.0-alpine3.20
        ports:
         - "5432"
        user: root
        env_file:
         - postgres.env
        healthcheck:
          test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
          interval: 3s
        volumes:
         - ${HOME}/volumes_docker/e-wallet/postgres-data:/var/lib/postgresql/data

