version: "3.9"
services:
    identidock:
        build:
         context: ../
         dockerfile: cmd/identidock/Dockerfile
        ports:
         - "8888:8888"
        depends_on:
         - dnmonster
         - redis
    dnmonster:
        image: amouat/dnmonster:latest
    redis:
        image: redis:7.2-alpine

