// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: imgstorage_service.proto

package imgstorageapi

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Null struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Null) Reset() {
	*x = Null{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imgstorage_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_imgstorage_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_imgstorage_service_proto_rawDescGZIP(), []int{0}
}

type Img struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Img  []byte `protobuf:"bytes,2,opt,name=img,proto3" json:"img,omitempty"`
}

func (x *Img) Reset() {
	*x = Img{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imgstorage_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Img) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Img) ProtoMessage() {}

func (x *Img) ProtoReflect() protoreflect.Message {
	mi := &file_imgstorage_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Img.ProtoReflect.Descriptor instead.
func (*Img) Descriptor() ([]byte, []int) {
	return file_imgstorage_service_proto_rawDescGZIP(), []int{1}
}

func (x *Img) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Img) GetImg() []byte {
	if x != nil {
		return x.Img
	}
	return nil
}

type NameImg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NameImg) Reset() {
	*x = NameImg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imgstorage_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameImg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameImg) ProtoMessage() {}

func (x *NameImg) ProtoReflect() protoreflect.Message {
	mi := &file_imgstorage_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameImg.ProtoReflect.Descriptor instead.
func (*NameImg) Descriptor() ([]byte, []int) {
	return file_imgstorage_service_proto_rawDescGZIP(), []int{2}
}

func (x *NameImg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InfImg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *InfImg) Reset() {
	*x = InfImg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imgstorage_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfImg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfImg) ProtoMessage() {}

func (x *InfImg) ProtoReflect() protoreflect.Message {
	mi := &file_imgstorage_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfImg.ProtoReflect.Descriptor instead.
func (*InfImg) Descriptor() ([]byte, []int) {
	return file_imgstorage_service_proto_rawDescGZIP(), []int{3}
}

func (x *InfImg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InfImg) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InfImg) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListImg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InfImg []*InfImg `protobuf:"bytes,1,rep,name=infImg,proto3" json:"infImg,omitempty"`
}

func (x *ListImg) Reset() {
	*x = ListImg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imgstorage_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListImg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImg) ProtoMessage() {}

func (x *ListImg) ProtoReflect() protoreflect.Message {
	mi := &file_imgstorage_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImg.ProtoReflect.Descriptor instead.
func (*ListImg) Descriptor() ([]byte, []int) {
	return file_imgstorage_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListImg) GetInfImg() []*InfImg {
	if x != nil {
		return x.InfImg
	}
	return nil
}

var File_imgstorage_service_proto protoreflect.FileDescriptor

var file_imgstorage_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x69, 0x6d, 0x67, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x69, 0x6d, 0x67, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x06, 0x0a, 0x04, 0x4e, 0x75, 0x6c, 0x6c, 0x22,
	0x2b, 0x0a, 0x03, 0x49, 0x6d, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6d,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x22, 0x1d, 0x0a, 0x07,
	0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6d, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x06,
	0x49, 0x6e, 0x66, 0x49, 0x6d, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x35,
	0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6d, 0x67, 0x12, 0x2a, 0x0a, 0x06, 0x69, 0x6e, 0x66,
	0x49, 0x6d, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6d, 0x67, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x49, 0x6d, 0x67, 0x52, 0x06, 0x69,
	0x6e, 0x66, 0x49, 0x6d, 0x67, 0x32, 0xac, 0x01, 0x0a, 0x0a, 0x49, 0x6d, 0x67, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d,
	0x67, 0x12, 0x0f, 0x2e, 0x69, 0x6d, 0x67, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x49,
	0x6d, 0x67, 0x1a, 0x10, 0x2e, 0x69, 0x6d, 0x67, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x4e, 0x75, 0x6c, 0x6c, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0b, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f,
	0x61, 0x64, 0x49, 0x6d, 0x67, 0x12, 0x13, 0x2e, 0x69, 0x6d, 0x67, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6d, 0x67, 0x1a, 0x0f, 0x2e, 0x69, 0x6d, 0x67,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6d, 0x67, 0x22, 0x00, 0x12, 0x35, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6d, 0x67, 0x12, 0x10, 0x2e, 0x69, 0x6d,
	0x67, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x1a, 0x13, 0x2e,
	0x69, 0x6d, 0x67, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49,
	0x6d, 0x67, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x3b, 0x69, 0x6d, 0x67, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_imgstorage_service_proto_rawDescOnce sync.Once
	file_imgstorage_service_proto_rawDescData = file_imgstorage_service_proto_rawDesc
)

func file_imgstorage_service_proto_rawDescGZIP() []byte {
	file_imgstorage_service_proto_rawDescOnce.Do(func() {
		file_imgstorage_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_imgstorage_service_proto_rawDescData)
	})
	return file_imgstorage_service_proto_rawDescData
}

var file_imgstorage_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_imgstorage_service_proto_goTypes = []interface{}{
	(*Null)(nil),                // 0: imgstorage.Null
	(*Img)(nil),                 // 1: imgstorage.Img
	(*NameImg)(nil),             // 2: imgstorage.NameImg
	(*InfImg)(nil),              // 3: imgstorage.InfImg
	(*ListImg)(nil),             // 4: imgstorage.ListImg
	(*timestamp.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_imgstorage_service_proto_depIdxs = []int32{
	5, // 0: imgstorage.InfImg.createdAt:type_name -> google.protobuf.Timestamp
	5, // 1: imgstorage.InfImg.updatedAt:type_name -> google.protobuf.Timestamp
	3, // 2: imgstorage.ListImg.infImg:type_name -> imgstorage.InfImg
	1, // 3: imgstorage.ImgStorage.UploadImg:input_type -> imgstorage.Img
	2, // 4: imgstorage.ImgStorage.DownloadImg:input_type -> imgstorage.NameImg
	0, // 5: imgstorage.ImgStorage.GetListImg:input_type -> imgstorage.Null
	0, // 6: imgstorage.ImgStorage.UploadImg:output_type -> imgstorage.Null
	1, // 7: imgstorage.ImgStorage.DownloadImg:output_type -> imgstorage.Img
	4, // 8: imgstorage.ImgStorage.GetListImg:output_type -> imgstorage.ListImg
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_imgstorage_service_proto_init() }
func file_imgstorage_service_proto_init() {
	if File_imgstorage_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_imgstorage_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Null); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imgstorage_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Img); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imgstorage_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameImg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imgstorage_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfImg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imgstorage_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListImg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_imgstorage_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_imgstorage_service_proto_goTypes,
		DependencyIndexes: file_imgstorage_service_proto_depIdxs,
		MessageInfos:      file_imgstorage_service_proto_msgTypes,
	}.Build()
	File_imgstorage_service_proto = out.File
	file_imgstorage_service_proto_rawDesc = nil
	file_imgstorage_service_proto_goTypes = nil
	file_imgstorage_service_proto_depIdxs = nil
}
