version: "3"
services:
    fibonacci:
        build:
         context: server/
         dockerfile: Dockerfile
        ports:
         - "8080:8080"
         - "55555:55555"
        links:
         - redis
    redis:
        image: redis:7.0.8-alpine

