# App setting
minimal_amount: 0.01

# HTTP server setting
http:
    host: localhost
    port: 8088

# database settings
db:
    driver: postgres
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    name: e-wallet

# logging settings
logger:
    filepath: ../logs/e-wallet-log.json
    level: debug # debug, info, warn, error

