# App setting
app:
    starting_balance: 100.00
    minimal_amount: 0.01

# HTTP server setting
http:
    host: e-wallet
    port: 8080

# database settings
db:
    driver: postgres
    host: postgres
    port: 5432
    user: wallet-user
    password: wallet-user
    name: wallet-db

# logging settings
logger:
    filepath:
    level: debug # debug, info, warn, error

