FROM alpine:3.20

MAINTAINER mrvin <v.v.vinogradovv@gmail.com>

RUN apk --no-cache add sqlite

WORKDIR /data

COPY schema/init_schema.up.sql /

CMD ["/bin/sh", "-c", "sqlite3 storage.db < /init_schema.up.sql"]