CREATE TABLE IF NOT EXISTS url(
	id serial PRIMARY KEY,
	alias TEXT NOT NULL UNIQUE,
	url TEXT NOT NULL,
	count NUMERIC(20,0) NOT NULL CHECK (count >= 0 AND count <= 18446744073709551615),
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_alias ON url(alias);
