# GRPC settings
hostGRPC: fibonacci
portGRPC: 55555

# HTTP settings
hostHTTP: fibonacci
portHTTP: 8080

# Redis database settings
db:
    hostDB: redis
    portDB: 6379
    passwordDB:
    nameDB: 0

