# HTTP server setting
http:
    host: localhost
    port: 8088

# database settings
db:
    driver: postgres
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    name: persons-db

# logging settings
logger:
    filepath: ../logs/persons-log.json
    level: debug # debug, info, warn, error

