# HTTP server setting
http:
    host: persons
    port: 8088

# database settings
db:
    driver: postgres
    host: postgres
    port: 5432
    user: persons-user
    password: persons-user
    name: persons-db

# logging settings
logger:
    filepath:
    level: debug # debug, info, warn, error

