services:
    notes-server:
        build:
         context: ../
         dockerfile: cmd/notes-server/Dockerfile
        ports:
         - "8088:8088" # REST API
        env_file:
         - ../configs/notes.env
        depends_on:
         - migrate

    migrate:
        image: migrate/migrate:v4.17.1
        command: ["-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable", "up"]
        depends_on:
          postgres:
            condition: service_healthy
        volumes:
         - ./../migrations:/migrations

    # Create service with PostgreSQL.
    postgres:
        image: postgres:16.4-alpine3.20
        ports:
         - "5432"
        user: root
        env_file:
         - ../configs/notes.env
        healthcheck:
          test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
          interval: 3s
        volumes:
         - ${HOME}/volumes_docker/notes/postgres-data:/var/lib/postgresql/data

