version: "3.9"
services:

    books:
        build:
         context: ../
         dockerfile: cmd/books-server/Dockerfile
        ports:
         - "55555:55555" # gRPC API
        depends_on:
          mysql:
            condition: service_healthy
        volumes:
         - ./../configs/books.yml:/etc/books/books.yml

    # Create service with MySQL.
    mysql:
        image: mysql:8.0
        ports:
         - "3306:3306"
        user: root
        environment:
         MYSQL_ROOT_PASSWORD: password123
         MYSQL_DATABASE: books-db
        healthcheck:
         test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        volumes:
         - ${HOME}/volumes_docker/books/mysql-data:/var/lib/mysql
         - ./init_schema.sql:/docker-entrypoint-initdb.d/init.sql

