build:
	docker-compose -f deployments/docker-compose.yml build

up:
	docker-compose -f deployments/docker-compose.yml up

down:
	docker-compose -f deployments/docker-compose.yml down

.PHONY: build up down
