CREATE TABLE IF NOT EXISTS hosts (
	name TEXT NOT NULL,
	ip INET NOT NULL UNIQUE PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS pings (
	ip INET references hosts(ip) on delete cascade,
	time NUMERIC(20,0) NOT NULL CHECK (time >= 0 AND time <= 18446744073709551615) DEFAULT 0,
	created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);
