# GRPC server settings
grpc:
    host: localhost
    port: 55555

# HTTP server setting
http:
    host: localhost
    port: 8080

# Redis database settings
db:
    host: redis
    port: 6379
    password:
    name: 0

