# GRPC server settings
grpc:
    host: fibonacci
    port: 55555

# HTTP server setting
http:
    host: fibonacci
    port: 8080

# Redis database settings
db:
    hostDB: redis
    portDB: 6379
    passwordDB:
    nameDB: 0

