services:
    persons:
        build:
         context: ../
         dockerfile: cmd/persons-server/Dockerfile
        ports:
         - "8080:8080" # REST API
        env_file:
         - ../configs/postgres.env
         - ../configs/persons.env
        depends_on:
         - migrate

    migrate:
        image: migrate/migrate:v4.18.3
        command: ["-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable", "up"]
        depends_on:
          postgres:
            condition: service_healthy
        volumes:
         - ./../migrations:/migrations

    # Create service with PostgreSQL.
    postgres:
        image: postgres:17.4-alpine3.21
        ports:
         - "5432"
        user: root
        env_file:
         - ../configs/postgres.env
        healthcheck:
          test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
          interval: 3s
        volumes:
         - ${HOME}/volumes_docker/persons/postgres-data:/var/lib/postgresql/data
