# database settings
db:
    driver: "sqlite3"
    path: ./storage.db
    host:
    port:
    user:
    password:
    name:

# HTTP server setting
http:
    host: url-shortener
    port: 8081
    is_https: false # Enable HTTPS
    https:
        cert_file: ../cert/cert.pem
        key_file: ../cert/key.pem


# logging settings
logger:
    filepath:
    level: debug # debug, info, warn, error
